name: Deploy HTML/CSS to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "ba48c949-ee0e-4425-9f14-d65481441c8e"
          tenant-id: "30bf9f37-d550-4878-9494-1041656caf27"
          subscription-id: "abe10fc9-2089-4a76-8fb7-e9a93870bafc"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lmsfewebapp'
          slot-name: 'Production'
          package: ./webapp
